# Generated by Django 2.1.2 on 2018-10-20 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_amount', models.FloatField()),
                ('receive_amount', models.FloatField()),
                ('resolved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('rules', models.TextField()),
                ('settle_time', models.DateTimeField()),
                ('category', models.CharField(choices=[('Sports', 'Sports'), ('eSports', 'eSports'), ('Entertainmnet', 'Entertainmnet'), ('Financials', 'Financials'), ('Politics', 'Politics'), ('Random', 'Random')], max_length=20)),
                ('pending', models.BooleanField(default=True)),
                ('settled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=200)),
                ('birth_date', models.DateField()),
                ('wallet_number', models.CharField(max_length=200)),
                ('balance', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='bet',
            name='no_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='no_bet', to='bets.User'),
        ),
        migrations.AddField(
            model_name='bet',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.Question'),
        ),
        migrations.AddField(
            model_name='bet',
            name='yes_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yes_bet', to='bets.User'),
        ),
    ]
