# Generated by Django 2.1.2 on 2018-10-20 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('wallet_number', models.CharField(max_length=200)),
                ('balance', models.FloatField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='bet',
            name='no_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='no_bet', to='bets.Profile'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='yes_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yes_bet', to='bets.Profile'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
